name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Adjust the Java version as needed

      - name: Set up Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8' # Android requires Java 8
          architecture: 'x64'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build


